baseURL = 'https://jean-lamarre.github.io'
languageCode = 'fr-US'
title = 'Jean Lamarre'
paginate = "8"
defaultContentLanguage = "fr"
theme = "spectral"

[params]
fancyTitle = '''Jean Lamarre'''
copyright = "Jean Lamarre"
description =  '''
Étudiant en génie logiciel
'''
startbuttonText = "Contacter Jean"
startbuttonLink = "#contact"
CvButtonText = "Télécharger mon CV"
CvButtonLink = "/pdf/CV_JEAN_LAMARRE.pdf"
body_is_markdown = true

[[params.menu.main]]
url = '#'
title = "Accueil"

# [[params.menu.main]]
# url = '/posts/'
# title = "template"

[[params.menu.main]]
url = '/club/'
title = "Activitées de club"

[[params.menu.main]]
url = '/games/'
title = "Mes jeux"

[[params.menu.main]]
url = '/professionnel/'
title = "Expériences professionnelles"

[[params.menu.main]]
url = '/projets/'
title = "Projets personnels"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Bienvenue dans mon univers'
body = '''  
Étudiant à l'ÉTS, j'ai débuté mon baccalauréat en génie 
logiciel à l'automne 2019 et j'aspire à devenir un professionnel dynamique,
motivant et accompli.
'''

[[params.one.icon]]
icon = "fa-laptop"
style = "1"
label = "Lorem"
url = "https://github.com/devcows/hugo-universal-theme/issues/127"

[[params.one.icon]]
icon = "fa-gamepad"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true
title = "Quelques jeux!"

Button = "Tous mes jeux"
ButtonLink = '/games/'

[[params.two.section]]
img = "images/cosmicExpresGamePlay.jpg"
title = "Cosmic Express"
body = '''
Deux joueurs guident un vaisseau  à travers le noyau d'un monde alien. 
Ils doivent travailler ensemble pour dégager les obstacles du chemin du vaisseau tout en exploitant les ressources nécessaires pour atteindre le prochain monde.

Prototype développé dans le cadre du concours universitaire Ubisoft.

[http://www.cosmicexpressgame.net](http://www.cosmicexpressgame.net)

{{<itchio id = "1919252" square = "true" linkback = "true" dark = "true" color = "2195b2">}}
'''

[[params.two.section]]
img = "images/UntitleJanitorGameImg.jpg"
title = "Untitle Janitor Game"
body = '''

Vous êtes Sir Géatan de Janitoria et vous devez aider à nettoyer des bureaux!

Ce jeu a été fait dans le contexte de projet de classe à l'ÉTS du cours LOG725.

{{<itchio id = "1484491" square = "true" linkback = "true" dark = "true" color = "2195b2">}}
 
'''


[[params.two.section]]
img = "images/DoggoUntilTomorrowImg.jpg"
title = "Doggo  Until Tomorrow"
body = '''
Dans ce jeu trop mignon, vous devrez aider les petits villageois à se nourrir en leur rapportant 
leur nourriture préférée! Observez comment ils vous remercieront de leur jolie petite voix!

Faites attention à la tombée du jour par contre...

{{<itchio id = "1377807" square = "true" linkback = "true" dark = "true" color = "2195b2">}}
'''

[[params.two.section]]
img = "images/LostRUsImg.jpg"
title = "Lost R' Us"
body = '''
Shaun et sa mère vont à l’épicerie ensemble.
 Mais malheur! Dans la foulée, le jeune garçon échappe la main de sa mère! 
 
 Il doit vite la retrouver, mais comment la retrouver alors que toutes ces dames se ressemblent tellement? 
 Vite!

{{<itchio id = "932135" square = "true" linkback = "true" dark = "true" color = "2195b2">}}
'''

[[params.two.section]]
img = "images/HotCocoImg.jpg"
title  = "Hot Coco"
body = '''
Tabascoco mène une vie paisible dans son volcan, bien allongé sous l'ombre de son palmier. Lorsque tout à coup, le volcan entre en éruption!

Pour s'en sortir, Tabascoco devra sauter de plateforme en plateforme avec un moyen de propulsion... peu conventionnel.

{{<itchio id = "757201" square = "true" linkback = "true" dark = "true" color = "2195b2">}}
'''

[params.three]
enable = false
title = 'Mes motivations'
body = '''
Je suis une personne curieuses qui est allumé par le développement de jeux vidéo, 
environnement et développement durable.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "[TODO]"

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "[TODO]"

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "[TODO]"

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "[TODO]"

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "[TODO]"

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "[TODO]"

[params.cta]
enable = true
title = "Contenu externe"
body = "Connectez-vous avec moi et visitez mes différents contenus externes."

[[params.cta.link]]
href = "https://www.linkedin.com/in/jean-lamarre/"
text = "LinkedIn"
special = true

[[params.cta.link]]
href = "https://eportfolio.etsmtl.ca/Portfolio/Clef/CpsRdS58ZgNz2X0vM33b"
text = "ePortfolio ETS"
special = true

[[params.cta.link]]
href = "https://github.com/Jean-Lamarre"
text = "GitHub"
special = true

[[params.cta.link]]
href = "https://johnytech6.itch.io/"
text = "Itch.io"
special = true

[params.contact]
formspree = "https://formspree.io/f/mqkjbqdp"
enable = true
title = "Contact"
body = '''
Laissez-moi un message. Au plaisir de vous rencontrer!\
jeanlamarredev@outlook.com
'''
email = "jeanlamarredev@outlook.com"
plain = false


[params.social]
itchio = "https://johnytech6.itch.io/"
linkedin = "https://www.linkedin.com/in/jean-lamarre/"
githubpages = "https://github.com/Jean-Lamarre/jean-lamarre.github.io"
github = "https://github.com/Jean-Lamarre"
#facebook = "https://www.facebook.com/ConjureETS"
#instagram = "https://www.instagram.com/conjure_ets/"
#ETS = "https://eportfolio.etsmtl.ca/Portfolio/Clef/CpsRdS58ZgNz2X0vM33b"
